title: St. Lawrence Regional Gathering
title-fr: Rassemblement régional Saint-Laurent
keywords: quaker, regional, gathering, Thousand Islands, meeting, Ottawa, Peterborough, friends, religious, society, religion, meditation
short_title: Regional Gathering
short_title-fr: Rassemblement régional
email: 
address:
adresse:
phone:

# This sets the point at which the website will switch from "desktop view" to "mobile/tablet view"
breakpoint: 1080px
verynarrow: 345px

webrick:
  headers:
    Cache-Control: max-age=31536000

# Certain types of media can be assigned to specific pages using this list. Everything in "media" is in the _include folder.

media_pages:
  - page_trans: sandbox
    media: slideshow.html
  
    # Turn alerts on and off using this variable below.
    # If you want alerts on all pages on the website, set 'alerts: all'.
    # If you want alerts on only certain pages, (the ones listed under "alert_pages", set "alerts: some"
    # Anything else, like '"alerton = "off"' and alerts will be off.

alerts: off
alert_pages:
  - page_trans: index

    #This section allows you to easily control which pages will have which bird and text animation
logo_left: 
  - animation: roll_bird1
    trans: rg
  - animation: swing-in1
    trans: index

logo_right:
  - animation: roll_bird2
    trans: links_history
  - animation: swing-in1
    trans: index

mobile_bird: 
  - animation: roll_bird1
    trans: links_history
  - animation: swing-in1
    trans: index

    # the text at the top of each page on wide screens
header_animation:
  - animation: focustext
    trans: index

    # the text at the top of each page on mobile/narrow screens

markdown: kramdown
include: ['_pages',".htaccess"]
exclude: ["backup","notes","Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"] 
sass:
    sass_dir: ./_sass
    style: compressed
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html,search-fr.html]
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: "assets/PDF"
    values:
      PDF: true
  - scope:
      path: "_pages" # an empty string here means all files in the project
    type: "pages"
    values:
      layout: "default"
      permalink: "/:basename"
  - scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
